version: 2
# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates
updates:
  - package-ecosystem: github-actions
    directory: .github
    commit-message:
      prefix: "ci"
    labels:
      - "type: cicd"
    groups:
      github-action-deps:
        patterns:
          - "*"
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /
    commit-message:
      prefix: "build"
    labels:
      - "type: build"
    groups:
      docker-deps:
        patterns:
          - "*"
    schedule:
      interval: weekly
