# SPDX-FileCopyrightText: Copyright 2020-2024, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0
#
changelog:
  exclude:
    labels:
      - "changelog: exclude"
      - "type: chore"
      - "type: style"
      - "scope: dev-infra"
      - "scope: docs-infra"
  categories:
    - title: 💥 Breaking changes
      labels:
        - "breaking"
    - title: ❌ Removals
      labels:
        - "type: drop"
    - title: 🗑️ Deprecations
      labels:
        - "type: deprecation"
    - title: 🔒️ Security
      labels:
        - "type: security"
    - title: ✨ Features
      labels:
        - "type: feature"
    - title: "🐛 Fixes"
      labels:
        - "type: fix"
    - title: ⚡️ Performance
      labels:
        - "type: performance"
    - title: 📝 Documentation
      labels:
        - "type: docs"
    - title: 🔧 Build
      labels:
        - "type: build"
    - title: 🍒 Miscellaneous
      labels:
        - "changelog: include"
        - "type: ci"
        - "type: refactor"
        - "type: test"
