# SPDX-FileCopyrightText: Copyright 2024, the RCSB PDB and contributors
# SPDX-PackageHomePage: https://github.com/rcsb/rcsb-chem-search
# SPDX-License-Identifier: BSD-3-Clause
#
# Check out https://pre-commit.com/ for documentation
minimum_pre_commit_version: 3.5.0
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
        args:
          - '--remove'
      - id: trailing-whitespace

  # --- Commit msg checks ---
  - hooks:
      - id: commitizen
        stages:
          - 'commit-msg'
    repo: https://github.com/commitizen-tools/commitizen
    rev: v3.13.0

  # --- Linters ---
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff
        args:
          -  '--fix-only'
        types_or:
          - python
          - pypirc
          - markdown
      - id: ruff-format
