# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

# Check out https://pre-commit.com/ for documentation
# ::tyranno:: rev: v$<< "dependency-groups" .dev .pypa_ver_spec_map(@) ."pre-commit" .pypa_ver_spec_min(@) >>
minimum_pre_commit_version: 4.2.0
repos:
  # Standard hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args:
          - --maxkb=256
      - id: forbid-new-submodules # ban Git submodules
      - id: check-case-conflict # ban ABC and abc both existing
      - id: check-illegal-windows-names # ban filenames that are illegal on Windows
      - id: check-merge-conflict # ban merge conflict markers
        args:
          - --assume-in-merge # otherwise skipped in rebase
      - id: check-symlinks # ban *broken* symlinks
      - id: check-shebang-scripts-are-executable # ensures all shebangs are executable
      - id: end-of-file-fixer # auto-add final \n
      - id: fix-byte-order-marker # auto-remove BOMs
      - id: trailing-whitespace # auto-remove end-of-line whitespace

  - repo: local
    hooks:
      - id: check-filenames
        name: Enforce file and directory naming conventions.
        entry: >-
          Path components may only use 'A-Za-z0-9_.,+=-' and cannot start with '-' or end with '.'.
        language: fail
        files: '[^/\w.,+=-]|(^|/)-|\.($|/)'
        stages:
          - pre-commit
      - id: pathvalidate
        name: Verify that paths are valid cross-platform.
        entry: pathvalidate --max-len 255 validate --
        language: python
        additional_dependencies:
          - pathvalidate-cli
        stages:
          - pre-commit

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.33.2
    hooks:
      - id: check-github-actions
      - id: check-github-workflows
      - id: check-compose-spec

  # UV lock and sync
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.7.21
    hooks:
      - id: uv-sync # first locks (without `--upgrade`)

  # Format and lint Python with Ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # ::tyranno:: rev: v$<< "dependency-groups" .dev .pypa_ver_spec_map(@) .ruff .pypa_ver_spec_max(@) >>
    rev: v0.12.3
    hooks:
      - id: ruff-check
        args:
          - --fix-only
          - --show-fixes
      - id: ruff-format

  # Format Justfile
  - repo: local
    hooks:
      - id: format-justfile
        name: Format the justfile using 'just --fmt'.
        entry: just --fmt --unstable
        pass_filenames: false
        language: system
        files: justfile
        stages:
          - pre-commit

  # Format various formats with Prettier
  # Don't update to 3.6 until this issue is fixed:
  # https://github.com/JoC0de/pre-commit-prettier/issues/3
  - repo: https://github.com/JoC0de/pre-commit-prettier
    rev: v3.5.3 # !!! DO NOT UPDATE !!!
    hooks:
      - id: prettier
        additional_dependencies:
          # ::tyranno:: - prettier@$<<_ .up(@, 3) .rev .trim_left(@, 'v') >>
          - prettier@3.5.3
          - prettier-plugin-ini@1.3.0 # https://www.npmjs.com/package/prettier-plugin-ini
          - prettier-plugin-toml@2.0.5 # https://www.npmjs.com/package/prettier-plugin-toml
          - prettier-plugin-sh@0.17.4
        args:
          - --experimental-ternaries # will be the default soon
          - --experimental-operator-position=start # might be made the default soon
          - --plugin=prettier-plugin-ini
          - --plugin=prettier-plugin-toml
          - --plugin=prettier-plugin-sh # also covers .properties, Dockerfile, .gitignore, and more
        # IMPORTANT: Sync this list with file types in this repo.
        # It's ok to list unused suffixes, but Prettier or a plugin must understand them.
        # See: https://prettier.io/docs/en/plugins.html
        # For Dockerfiles, we allow both `xyz.dockerfile` (as suggested in official docs)
        # and `Dockerfile.xyz` (which is at least as common).
        # WARNING: prettier-plugin-sh butchers Dockerfiles occasionally.
        files: >-
          (?x)
          \. (md|mdx|json|yaml|yml|toml|ini|cfg|properties|sh|ts|js|html|less|css|dockerfile) $
          | ^ Dockerfile (\. [^.]*+)?+ $
          | \. [^.]*ignore $

  - repo: https://github.com/tcort/markdown-link-check
    rev: v3.13.7
    hooks:
      - id: markdown-link-check
        args:
          - -q
        stages:
          - manual
