# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

# Check out https://pre-commit.com/ for documentation
minimum_pre_commit_version: 4.2.0
repos:
  # Standard hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args:
          - --maxkb=256
      - id: forbid-new-submodules # ban Git submodules
      - id: check-case-conflict # ban ABC and abc both existing
      - id: check-illegal-windows-names # ban filenames that are illegal on Windows
      - id: check-merge-conflict # ban merge conflict markers
        args:
          - --assume-in-merge # otherwise skipped in rebase
      - id: check-symlinks # ban *broken* symlinks
      - id: end-of-file-fixer # auto-add final \n
      - id: fix-byte-order-marker # auto-remove BOMs
      - id: trailing-whitespace # auto-remove end-of-line whitespace

  # UV lock and sync
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.6.14
    hooks:
      - id: uv-sync

  # Format and lint Python with Ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.5
    hooks:
      - id: ruff
        args:
          - --fix-only
      - id: ruff-format

  # Format various formats with Prettier
  - repo: https://github.com/JoC0de/pre-commit-prettier
    rev: v3.5.3
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.5.3
          - prettier-plugin-ini@1.3.0
          - prettier-plugin-toml@2.0.1
          - prettier-plugin-sh@0.14.0
        args:
          - --experimental-ternaries # will be the default soon
          - --experimental-operator-position=start # won't be the default but should be
          - --plugin=prettier-plugin-ini
          - --plugin=prettier-plugin-toml
          - --plugin=prettier-plugin-sh # also covers .properties and Dockerfile
        # IMPORTANT: Sync this list with file types in this repo.
        # It's ok to list unused suffixes, but Prettier or a plugin must understand them.
        # See: https://prettier.io/docs/en/plugins.html
        files: \.(md|mdx|json|yaml|yml|toml|ini|cfg|properties|sh|ts|js|html|less|css)$|^Dockerfile$|^\..+ignore$

  - repo: https://github.com/tcort/markdown-link-check
    rev: v3.13.7
    hooks:
      - id: markdown-link-check
        args:
          - -q
        stages:
          - manual
