services:
  app:
    build: .
    volumes:
      - .:/var/app/:cached
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/app
    depends_on:
      mongodb:
        condition: service_healthy

  mongodb:
    image: mongo:8
    restart: unless-stopped
    command: mongod --quiet
    volumes:
      - mongo:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand({ping:1})"]
      interval: 15s
      start_interval: 2.5s
      start_period: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo:
