services:
  web:
    build: .
    volumes:
      - .:/var/lib/app/
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/app
    depends_on:
      - mongo
    develop:
      watch:
        - action: sync
          path: .
          target: /app

volumes:
  mongo:

networks:
  default:
    enable_ipv6: true
