services:
  app:
    build: .
    volumes:
      - .:/var/app/:cached
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/app
    depends_on:
      mongodb:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: .
          target: /var/app

  mongodb:
    image: mongo:8
    restart: unless-stopped
    command: mongod --quiet --logpath /dev/null
    volumes:
      - mongo:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 15s
      start_interval: 2.5s
      start_period: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo:
