blank_issues_enabled: true
contact_links:
  - name: Ask a question
    # ::tyranno:: url: https://github.com/$<<.vendor>>/$<<project.name>>/discussions/new?category=q-a
    url: https://github.com/rcsb/py-rcsbchemsearch/discussions/new?category=q-a
    about: Get help with something
  - name: Security issue
  - url: https://github.com/rcsb/py-rcsbchemsearch/security/advisories/new
    about: Report a security issue
