# SPDX-FileCopyrightText: Copyright 2020-2024, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

name: "✨ Feature"
description: "Feature request"
labels:
  - "type: feature"
  - "state: awaiting triage"

body:
  - type: textarea
    id: description
    attributes:
      label: What is the feature request?
      placeholder: Describe the feature you would like.
    validations:
      required: true
