# SPDX-FileCopyrightText: Copyright 2020-2024, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

name: "⚡️ Performance"
description: "Performance issue"
labels:
  - "type: performance"
  - "state: awaiting triage"

body:
  - type: textarea
    id: description
    attributes:
      label: What is the performance issue?
      placeholder: Detail your steps and where the performance dropped.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version are you running?
  - type: dropdown
    id: os
    attributes:
      label: What OS types are you seeing the problem on?
      multiple: true
      options:
        - Windows
        - Linux
        - macOS
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Chrome
        - Firefox
        - Edge
        - Safari
        - Opera
        - Samsung Internet
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output.
      render: shell
