# Declare variables to be passed into your templates.

replicaCount: 2
revisionHistoryLimit: 3

# vaultSecretStoreName is the name of the ClusterSecretStore resource to pull secret credentials
vaultSecretStoreName: "rcsb-vault"

startupProbe:
  httpGet:
    path: /alive
  failureThreshold: 5
  periodSeconds: 12
  initialDelaySeconds: 30

readinessProbe:
  httpGet:
    path: /ready
  failureThreshold: 10
  periodSeconds: 12
  initialDelaySeconds: 30

livenessProbe:
  httpGet:
    path: /alive
  failureThreshold: 3
  periodSeconds: 12
  initialDelaySeconds: 30

rookCeph:
  metadataPoolSize: 3
  dataPoolSize: 3
  preserveFilesystemOnDelete: true
  reclaimPolicy: Retain
  allowVolumeExpansion: true
  pvcAccessModes:
    - ReadOnlyMany

image:
  repository: harbor.devops.k8s.rcsb.org/rcsb/rcsb-chem-search
  pullPolicy: Always

imagePullSecrets: "harbor-docker-registry-conf"

deploymentStrategy:
  # https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy
  # Type is either RollingUpdate or Recreate
  type: "RollingUpdate"
  # For rolling update, what percentage of total pods can be created above desired amount
  maxSurge: 25%
  # For rolling update, what percentage of total pods can be brought down to update
  maxUnavailable: 25%

podSecurityContext:
  fsGroup: 33
  runAsNonRoot: true
  runAsUser: 33
  runAsGroup: 33
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false

service:
  type: ClusterIP
  port: 80
  containerPort: 8080

usePersistentVolume: true
persistentVolumeMountPath: "/opt/chemsearch-data"
persistentVolumeReadOnly: true
