# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

# "Function" workflow: that runs `uv lock --upgrade`, commits, and pushes.

on:
  workflow_call:

jobs:
  bump-deps:
    runs-on: ubuntu-latest
    env:
      UV_NO_SYNC: true
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]' || exit $?
          git config --global user.email 'github-actions[bot]@users.noreply.github.com' || exit $?
      - name: Upgrade the lock file
        run: |
          uv lock --upgrade || exit $?
          if git diff --quiet uv.lock; then
            git commit --no-verify -m "build: update lock file" uv.lock || exit $?
          else
            printf "No changes to uv.lock to commit\n"
          fi
      - name: Upgrade the pre-commit config
        run: |
          uv sync --frozen --only-group precommit || exit $?
          uv run pre-commit install || exit $?
          uv run pre-commit autoupdate || exit $?
          if git diff --quiet .pre-commit-config.yaml; then
            git commit --no-verify -m "ci: upgrade pre-commit config" .pre-commit-config.yaml || exit $?
          else
            printf "No changes to .pre-commit-config.yaml to commit.\n"
          fi
      - name: Push changes
        run: |
          git push || exit $?
