# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

# "Function" workflow that checks basic things via pre-commit hooks.

on:
  workflow_call:

jobs:
  check-hooks:
    runs-on: ubuntu-latest
    env:
      UV_NO_SYNC: true
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - name: Run some pre-commit hooks
        run: |
          uv sync --frozen --only-group precommit || exit $?
          chk() {
            uv run pre-commit run --all-files $1 || exit $?
          }
          chk check-added-large-files
          chk forbid-new-submodules
          chk check-case-conflict
          chk check-illegal-windows-names
          chk check-merge-conflict
          chk check-symlinks
          # These auto-fix, but we're not committing the changes:
          chk fix-byte-order-marker
          chk end-of-file-fixer
          chk trailing-whitespace
