# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

# "Function" workflow that lints with Ruff.

on:
  workflow_call:
    inputs:
      rules:
        type: string
        default: ""
      glob:
        type: string
        default: .

jobs:
  check-ruff:
    runs-on: ubuntu-latest
    env:
      UV_NO_SYNC: true
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - run: |
          uv sync --locked --only-group ruff || exit $?
      - name: Check Ruff formatting
        run: |
          uv run ruff format --check ${{ inputs.glob }} || exit $?
      - name: Check Ruff rules
        run: |
          if [[ -z "${{ inputs.rules }}" ]]; then
            uv run ruff check --no-fix ${{ inputs.glob }} || exit $?
          else
            uv run ruff check --no-fix --select "${{ inputs.rules }}" ${{ inputs.glob }} || exit $?
          fi
