# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

# "Function" workflow that publishes a release to PyPI.
# Requires `_build_dist.yaml`.

on:
  workflow_call:
    inputs:
      repository:
        type: string
        required: true
        description: Either 'pypi' or 'testpypi'.

jobs:
  publish-pypi:
    # This job publishes the package to PyPI.
    name: Publish to PyPi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - name: Download dist/ GH workflow artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-${{ github.ref_name }}
      - name: Publish to PyPi using uv.
        # See: https://docs.pypi.org/trusted-publishers/adding-a-publisher/
        run: |
          uv publish || exit $?
