# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

# "Function" workflow that runs formatters and auto-fixers, commits, and pushes the changes.

on:
  workflow_call:
    inputs:
      all-files:
        type: boolean
        default: false

jobs:
  reformat:
    name: Reformat and auto-fix modified files
    if: ${{ github.event_name == 'pull_request' || inputs.all-files == true }}
    runs-on: ubuntu-latest
    env:
      # For historical reasons, the GH CLI uses GH_TOKEN instead of GITHUB_TOKEN
      # https://github.com/github/docs/issues/21930
      GH_TOKEN: ${{ github.token }}
      UV_NO_SYNC: true
    steps:
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]' || exit $?
          git config --global user.email 'github-actions[bot]@users.noreply.github.com' || exit $?
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - run: |
          uv sync --locked --only-group precommit || exit $?
      - name: Run Ruff auto-fix
        run: |
          if [[ "${{ inputs.all-files }}" == "true" ]]; then
            uv run pre-commit run ruff --all-files || exit $?
          else
            uv run pre-commit run ruff \
              --from-ref ${{ github.event.pull_request.base.sha }} \
              --to-ref ${{ github.event.pull_request.head.sha }} \
              || exit $?
          fi
      - name: Commit Ruff auto-fixes (if any)
        run: |
          if ! git diff --quiet . ; then
            git commit -m "fix: auto-fix lint violations" . || exit $?
          fi
      - name: Reformat
        run: |
          if [[ "${{ inputs.all-files }}" == "true" ]]; then
            uv run pre-commit run ruff-format --all-files
            uv run pre-commit run prettier --all-files
          else
            uv run pre-commit run ruff-format
              --from-ref ${{ github.event.pull_request.base.sha }} \
              --to-ref ${{ github.event.pull_request.head.sha }} \
              || true
            uv run pre-commit run prettier
              --from-ref ${{ github.event.pull_request.base.sha }} \
              --to-ref ${{ github.event.pull_request.head.sha }} \
              || true
      - name: Commit formatter changes (if any)
        run: |
          if ! git diff --quiet . ; then
            git commit -m "style: auto-fix lint violations and autoformat" . || exit $?
          fi
      - name: Push changes (if any)
        run: |
          git push || exit $?
