# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

# "Function" workflow that runs `_run-pytest-single` for each OS and Python version.
# See:
# https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast

on:
  workflow_call:
    inputs:
      ref:
        type: string
        description: The branch or tag
      markers:
        type: string
        default: not ux
      retention-days:
        type: number
        default: 0
      fail-fast:
        type: boolean
        default: true
        description: "Potentially useful if coverage reports are generated (`retention-days` > 0)."
      max-parallel:
        type: number
        default: 1
        description: "Increase when testing important branches; leave at 1 for PRs."

env:
  REF: ${{ inputs.ref || github.ref_name }}

jobs:
  run-tests:
    name: Test ${{ env.REF }}
    strategy:
      fail-fast: ${{ inputs.fail-fast }} # Doesn't affect the status of the `run-tests` job.
      max-parallel: ${{ inputs.max-parallel }}
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        python:
          # ::tyranno-start:: $<<.python-builds|yaml(@)>>
          - "3.13"
          # :tyranno-end
    uses: ./.github/workflows/_run-pytest-single.yaml
    with:
      ref: ${{ env.REF }}
      os: ${{ matrix.os }}
      python: ${{ matrix.python }}
      retention-days: ${{ inputs.retention-days }}
      markers: ${{ inputs.markers }}
