# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0
#
# SPDX-FileCopyrightText: Copyright 2024, Contributors to rcsb-chem-search
# SPDX-PackageHomePage: https://github.com/rcsb/rcsb-chem-search
# SPDX-License-Identifier: BSD-3-Clause
#
# Modified from Tyrannosaurus <https://github.com/dmyersturnbull/tyrannosaurus>.

# Checks links.

name: check-links
run-name: >
  ${{ github.workflow }}
  :: ${{ github.event_name }}
  :: ${{ github.ref_type }}:${{ github.ref_name }}
  :: @${{ github.actor }}

on:
  merge_group:
    types:
      - checks_requested
  pull_request:
    types:
      - ready_for_review
      - synchronize
      - edited
    paths:
      - "**/*.md"
  issue_comment:
    types:
      - created
      - edited

permissions:
  contents: read
  statuses: read
  actions: read

jobs:
  check-links:
    name: Test building docs
    runs-on:
      - self-hosted
      - ubuntu-22.04
    if: >
      (
        github.event_name == 'pull_request'
        && (
          github.event.action == 'ready_for_review'
          || (
            contains(fromJSON('["opened", "edited", "synchronize"]'), github.event.action)
            && (
              !contains(github.event.pull_request, 'draft')
              || github.event.pull_request.draft == false
            )
          )
        )
      ) || (
        github.event_name == 'issue_comment'
        && contains(fromJSON('["created", "edited"]'), github.event.action)
        && contains(fromJSON('["/please-review", "/please-check-links"]'), github.event.comment.body)
      )
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}
      - uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.13"
          enable-cache: true
      - uses: actions/checkout@v4
      - name: Run linkspector
        uses: umbrelladocs/action-linkspector@v1
        with:
          github_token: ${{ secrets.github_token }}
          # Optional:
          # reporter: ${{ github.event_type == 'schedule' && 'github-check' || 'github-pr-review' }}
