# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0
#
# SPDX-FileCopyrightText: Copyright 2024, Contributors to rcsb-chem-search
# SPDX-PackageHomePage: https://github.com/rcsb/rcsb-chem-search
# SPDX-License-Identifier: BSD-3-Clause
#
# Modified from Tyrannosaurus <https://github.com/dmyersturnbull/tyrannosaurus>.

# When a commit is pushed to main or releases/**, runs tests and either opens an issue or uploads coverage reports.
name: Main-test
run-name: Test ${{ github.ref_name }} (${{ github.sha }})

on:
  push:
    paths:
      - pyproject.toml
      - src/**/*.py
      - tests/**/*.py
    branches:
      - main
      - master
      - releases/**

concurrency: # More restrictive groups defined on jobs.
  group: main-test-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
  IS_MAIN: ${{ github.ref_name == 'main' || github.ref_name == 'master' }}

jobs:
  test:
    uses: ./.github/workflows/_run-pytest.yaml
    with:
      retention-days: 1 # Only to upload coverage reports.
  create-issue:
    if: ${{ failure() }}
    needs: test
    name: Open a GitHub issue if tests failed
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create GitHub issue
        env:
          # For historical reasons, the GH CLI uses GH_TOKEN instead of GITHUB_TOKEN
          # https://github.com/github/docs/issues/21930
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue create \
            --title "Test failure(s) on ${{ github.ref_name }}" \
            --body "See: [run #${{ github.run_id }}](${{ env.RUN_URL }})" \
            --label "type: bug"
          exit 1
