# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0
#
# SPDX-FileCopyrightText: Copyright 2024, Contributors to rcsb-chem-search
# SPDX-PackageHomePage: https://github.com/rcsb/rcsb-chem-search
# SPDX-License-Identifier: BSD-3-Clause
#
# Modified from Tyrannosaurus <https://github.com/dmyersturnbull/tyrannosaurus>.

# Responds to "command" comments on pull requests.
name: PR-bot
run-name: Comment by ${{ github.sender.login }} on PR ${{ github.event.pull_request.number }}

on:
  issue_comment:
    types:
      - created
      - edited

permissions:
  contents: read

jobs:
  audit:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/please-audit') }}
    concurrency:
      group: audit-${{ github.ref_name }}
      cancel-in-progress: true
    uses: ./.github/workflows/_check-ruff.yaml
    with:
      rules: S

  lint:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/please-lint') }}
    concurrency:
      group: lint-${{ github.ref_name }}
      cancel-in-progress: true
    uses: ./.github/workflows/_check-ruff.yaml

  check-docker:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/please-check-docker') }}
    concurrency:
      group: check-docker-${{ github.ref_name }}
      cancel-in-progress: true
    uses: ./.github/workflows/_check-docker.yaml

  check-docs:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/please-check-docs') }}
    concurrency:
      group: check-docs-${{ github.ref_name }}
      cancel-in-progress: true
    uses: ./.github/workflows/_check-docs.yaml

  upgrade:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/please-upgrade') }}
    concurrency:
      group: fixup-${{ github.ref_name }} # Group shared with `reformat`.
      # DO NOT cancel this workflow if it's already running.
    permissions:
      contents: write
    uses: ./.github/workflows/_bump-deps.yaml

  reformat:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/please-reformat') }}
    concurrency:
      group: fixup-${{ github.ref_name }} # Group shared with `upgrade`.
      # DO NOT cancel this workflow if it's already running.
    permissions:
      contents: write
    uses: ./.github/workflows/_reformat.yaml

  test:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/please-test') }}
    concurrency:
      group: test-${{ github.ref_name }} # Group shared with `unit-test`.
      cancel-in-progress: true # Let `test` cancel `test-fast` (and `test`).
    uses: ./.github/workflows/_run-pytest.yaml

  test-fast:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/please-test-fast') }}
    concurrency:
      group: test-${{ github.ref_name }} # Group shared with `test`.
      # Don't let `test-fast` cancel `test`.
    uses: ./.github/workflows/_run-pytest.yaml
    with:
      markers: not (ux or slow or net)
