# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

# Checks basic things on every push to a PR.
name: PR-quick-check
run-name: Quick-check PR ${{ github.event.pull_request.number }} by ${{ github.event.pull_request.user.login }}

on:
  pull_request:

concurrency:
  group: check-basics-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  check-hooks:
    if: ${{ !contains(github.event.pull_request, 'draft') || !github.event.pull_request.draft }}
    uses: .github/workflows/_check-hooks.yaml
