# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0
#
# SPDX-FileCopyrightText: Copyright 2024, Contributors to rcsb-chem-search
# SPDX-PackageHomePage: https://github.com/rcsb/rcsb-chem-search
# SPDX-License-Identifier: BSD-3-Clause
#
# Modified from Tyrannosaurus <https://github.com/dmyersturnbull/tyrannosaurus>.

# Runs the release process when `validate` completes successfully (after a tag is pushed).
name: Publish
run-name: >-
  ${{ github.event.workflow_run.conclusion == 'success' && 'Publish' || 'Ignore' }} ${{ github.ref_name }}

on:
  workflow_run:
    types:
      - completed
    workflows:
      - validate

concurrency:
  # Only allow one publish workflow to run at a time.
  # This prevents accidental double-publishes and avoids upsetting external services.
  # There's also little reason to run more than one at a time.
  group: publish
  # DO NOT cancel this workflow if it's already running.

permissions:
  contents: read

jobs:
  accept:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: [self-hosted, buildchain]
    steps:
      - run: |
          printf "Accepted %s for release.\n" "${{ github.ref_name }}"
  publish-github:
    needs: accept
    permissions:
      pages: write
    uses: ./.github/workflows/_publish-github.yaml
  #  publish-pypi:
  #    needs: accept
  #    uses: ./.github/workflows/_publish-pypi.yaml
  #    secrets: inherit
  #  publish-docker:
  #    needs: accept
  #    uses: ./.github/workflows/_publish-docker.yaml
  #    secrets: inherit

  deploy-helm:
    name: Push to Harbor
    permissions:
      contents: write
    # https://github.com/rcsb/devops-cicd-github-actions/blob/master/.github/workflows/workflow-docker.yaml
    uses: rcsb/devops-cicd-github-actions/.github/workflows/workflow-docker.yaml@master
    with:
      repo_project: ${{ github.repository_owner }}
      docker_image_name: ${{ github.event.repository.name }}
      mainline_branch: ${{ github.ref_name }} # Tag name
