# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0
#
# SPDX-FileCopyrightText: Copyright 2024, Contributors to rcsb-chem-search
# SPDX-PackageHomePage: https://github.com/rcsb/rcsb-chem-search
# SPDX-License-Identifier: BSD-3-Clause
#
# Modified from Tyrannosaurus <https://github.com/dmyersturnbull/tyrannosaurus>.

# Runs the release process when `validate` completes successfully (after a tag is pushed).
name: Publish
run-name: >-
  ${{ github.event.workflow_run.conclusion == 'success' && 'Publish' || 'Ignore' }} ${{ github.ref_name }}

on:
  workflow_run:
    types:
      - completed
    workflows:
      - validate

concurrency:
  # Only allow one publish workflow to run at a time.
  # This prevents accidental double-publishes and avoids upsetting external services.
  # There's also little reason to run more than one at a time.
  group: publish
  # DO NOT cancel this workflow if it's already running.

permissions:
  contents: read

jobs:
  accept:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    outputs:
      is_real: ${{ steps.check-ref.outputs.is_real }}
    steps:
      - id: check-ref
        run: |
          if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "is_real=true" >> $GITHUB_OUTPUT
            printf "Accepted %s for full release.\n" "${{ github.ref_name }}"
          else
            printf "Accepted %s for preview/test release.\n" "${{ github.ref_name }}"
          fi
  publish-github:
    needs: accept
    permissions:
      contents: write
    uses: ./.github/workflows/_publish-github.yaml
    secrets: inherit
  publish-pypi:
    needs: accept
    uses: ./.github/workflows/_publish-pypi.yaml
    with:
      repository: ${{ needs.accept.outputs.is_real == 'true' && 'pypi' || 'testpypi' }}
    secrets: inherit
