# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0
#
# SPDX-FileCopyrightText: Copyright 2024, Contributors to rcsb-chem-search
# SPDX-PackageHomePage: https://github.com/rcsb/rcsb-chem-search
# SPDX-License-Identifier: BSD-3-Clause
#
# Modified from Tyrannosaurus <https://github.com/dmyersturnbull/tyrannosaurus>.

# Runs Pytest tests on a matrix of (OS, Python version).

name: pytest
run-name: >
  ${{ github.workflow }}
  :: ${{ github.event_name }}
  :: ${{ github.ref_type }}:${{ github.ref_name }}
  :: @${{ github.actor }}

on:
  merge_group:
    types:
      - checks_requested
  pull_request:
    types:
      - ready_for_review
      - synchronize
      - opened
      - edited
    paths:
      - "**/*.py"
      - pyproject.toml
  issue_comment:
    types:
      - created
      - edited

permissions:
  contents: read
  statuses: write
  actions: read
  security-events: write

# Uncomment to make coverage use a more modern, experimental core
# https://coverage.readthedocs.io/en/7.6.10/cmd.html#execution-coverage-run
#env:
#  COVERAGE_CORE: sysmon

jobs:
  pytest:
    name: Run tests for ${{ matrix.os }}, Python ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    if: >
      (
        github.event_name == 'pull_request'
        && (
          github.event.action == 'ready_for_review'
          || (
            contains(fromJSON('["opened", "edited", "synchronize"]'), github.event.action)
            && (
              !contains(github.event.pull_request, 'draft')
              || github.event.pull_request.draft == false
            )
          )
        )
      ) || (
        github.event_name == 'issue_comment'
        && contains(fromJSON('["created", "edited"]'), github.event.action)
        && contains(fromJSON('["/please-review", "/please-test"]'), github.event.comment.body)
      )
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python:
          - "3.13"
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}
      - uses: astral-sh/setup-uv@v5
        with:
          python-version: "${{ matrix.python }}"
          enable-cache: true
      - name: Install dependencies and run tests
        id: test
        run: |
          uv run --locked pytest -m 'not ux'
      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.os }}-${{ matrix.python }}
          path: coverage.json
          if-no-files-found: error
